### ISSUE TITLE
Why directives and pipes are in theme module?

### ISSUE THREAD

**Issue by rahulkundu0310** [rajaramtt/angular6-realworld-highly-scalable-application#1]
Hello Raja, first of all thank you for creating this awesome folder structure. basically it is not an issue I have some questions.

Why you have imported pipes and directives and NG bootstrap modules in theme module. As you have mentioned that core module should contain singleton things.

I am trying to use your folder structure in one of my projects, where I am using NGX bootstrap.  Should I create a theme module same as yours which will contain all NGX bootstrap imports and pipes, directives and all third party npm packages. Or i will use these all in core module . Please suggest.

I am a beginner so asking one more silly question. Why you have use forRoot for theme module and not for core module?

**Comment by rajaramtt** [comment]
@rahulkundu0310   Please use  **SharedModule** is where any shared components, **pipes/filters**, and services should go.
